name: gol-fast
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - numpy
  - sqlalchemy
  - pip:
      - dearpygui
      - hydra-core
      - hydra-colorlog
      - typeguard
      - yapf
